version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # graphql-app:
  #   image: romaniukvadim/graphql-app
  #   container_name: graphql-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/todo_app_romani
  #     GRAPHQL_SERVLET_MAPPING: /graphql
  #     GRAPHQL_SERVLET_CORSENABLED: "true"
  #     GRAPHIQL_ENABLED: "true"
  #     GRAPHQL_SERVLET_ENABLED: "true"
